CREATE TABLE `person`(
    `Id` int(10) UNSIGNED NULL DEFAULT NULL,
    `FirstName` VARCHAR(50) NULL DEFAULT NULL,
    `LastName` VARCHAR(50) NULL DEFAULT NULL,
    `Address` VARCHAR(50) NULL DEFAULT NULL,
    `Gender` VARCHAR(15) NULL DEFAULT NULL
  )
  ENGINE = InnoDB;

#ALTER TABLE person CHANGE Id Id INT(10) AUTO_INCREMENT PRIMARY KEY;